FORMAT: 1A
HOST: http://api.stg.kioson.biz/api/v1

# de453f5c6caba980baa12b6eb31543dc

bridging for existing API to New API format

## App [/mobile]

### Check Version [POST /mobile/check-version]

+ Request (application/json)

        {
            "device_version": "1.0"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Aplikasi versi 1.0 sudah nggak mendukung usahamu lagi. Segera update aplikasimu sekarang!",
            "data": {
                "current_version": "7.0",
                "url": "http://refro.kioson.biz/ipayrefroserver/IPAY_ReFro.apk.rar"
            }
        }

### Slider [GET /mobile/slider]

+ Response 200 (text/html)

### Home Banner [GET /mobile/home-banner]

+ Response 200 (text/html)

### Technical Help [GET /mobile/technical-help]
status: todo

+ Response 200 (application/json)

### Configuration [GET /mobile/configuration]
status: todo

+ Response 200 (application/json)

## Preset [/presets]

### Shop Types [GET /shop_types]
status: todo

+ Response 200 (application/json)

### All Operators [GET /operators]
status: todo

+ Response 200 (application/json)

## Auth [/auth]

### Auth Register [POST /auth/register]

+ Request (application/json)

        {
            "otp": "123456",
            "name": "User Skyshi",
            "email": "user@skyshi.com",
            "phone_number": "082111333599",
            "password": "12345678",
            "referral_code": ""
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Pendaftaran Kioson Anda akan diproses. ID Kioson Cash Point (ID KCP) Anda akan dibuat dalam periode 24 jam dan akan dikomunikasikan ke Anda melalui SMS. Untuk pertanyaan dan informasi lebih lanjut, hubungi Call Center Kioson di 0812-9556-8383 (TELKOMSEL), 0818-0721-8383 (XL), 0857-7625-8383 (INDOSAT), dan 0899-983-8383 (THREE). Terima Kasih",
            "data": {}
        }

### Auth Login [POST /auth/login]

+ Request (application/json)

        {
            "username": "rzzy",
            "password": "12345"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaW4iOiJiYzBiZmMzYWQwNGFlNGE4YTY1NDQ0ZWRkMzAwMDQxNiIsInNlc3Npb25faWQiOiI0N2I3OWEwYy1jYTZmLTExZTctYSIsInJldGFpbGVyX2lkIjoicnp6eSIsImlhdCI6MTUxMDc5NjQ5NSwiZXhwIjoxNTExNDAxMjk1fQ.WOViLhW5QmD5Go305BWdoT-22-CpRUUCNjCNHz5z04w"
            }
        }

### Auth Logout [GET /logout]
status: todo

+ Response 200 (application/json)

## OTP [/otp]

### Resend OTP [POST /otp/send]

+ Request (application/json)

        {
            "phone_number": "082123456789"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "OTP will sent to your register mobile number",
            "data": {}
        }

## User [/user]

### Service Location [GET /user/service-location]
status: todo

+ Response 200 (application/json)

### Information [GET /user]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "website": "N/A",
                "retailer_id": "RZZY",
                "icp_category_name": "KCP PREMIUM",
                "distributer_id": "D0A",
                "first_name": "Satrio",
                "last_name": "Wisnugroho",
                "mobile_no": "085694946170",
                "mobno": "085694946170",
                "dist_first_name": "IPay Tech",
                "dist_lastt_name": "India",
                "icc_category_name": "KCC PREMIUM",
                "village": "KUTUH",
                "constituency": "KUTA SELATAN",
                "distmobnum": "9703437763",
                "hno": "23",
                "street": "AXA JAKARTAX",
                "locality": "Tampomas Sleman",
                "landmark": "XXX",
                "city": "AXA JAKARTA",
                "district": "BADUNG",
                "pincode": "123456",
                "state": "BALI",
                "business_name": "Wisnu Cell",
                "business_type": "TOKO PULSA",
                "landline": "",
                "email": "wisnugrohosatrio@gmail.com",
                "customer_care": "+62-818-0721-8383,+62-812-9556-8383,+62-899-983-8383,+62-857-7625-8383,+62-817-233-3838"
            }
        }

### Update Profile [PUT /user]

+ Request (application/json)

        {
            "name": "Satrio Wisnugroho",
            "email": "wisnugrohosatrio@gmail.com",
            "store_name": "Wisnu Cell",
            "store_phone": "082138844644",
            "store_type": "TOKO PULSA",
            "street": "Tampomas Sleman",
            "province": "BALI",
            "district": "BADUNG",
            "city": "KUTA SELATAN",
            "village": "KUTUH",
            "zip_code": "123456",
            "store_street": "Tampomas Sleman",
            "store_province": "BALI",
            "store_district": "BADUNG",
            "store_city": "KUTA SELATAN",
            "store_village": "KUTUH",
            "store_zip_code": "123456",
            "latitude": "-7.77135075",
            "longitude": "110.34580316",
            "isShop": "0",
            "id_image": "base64",
            "store_image": "base64",
            "selfie_image": "base64"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Udpated Successfully.",
            "data": {}
        }

### Pin [GET /user/pin]
status: todo

+ Response 200 (application/json)

### List Messages [GET /user/messages]
status: todo

+ Response 200 (application/json)

### Update App Version [PUT /user/app-version]
status: todo

+ Response 200 (application/json)

### Loan Activity [POST /user/loan-activity]
status: todo

+ Response 200 (application/json)


### Balances [GET /user/balances]
status: todo

+ Response 200 (application/json)

## Order [/orders]

### List Orders [GET /]
status: todo

+ Response 200 (application/json)

## Location [/location]

### States [GET /location/states]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": 1,
                    "name": "BALI"
                },
                {
                    "id": 2,
                    "name": "BANGKA BELITUNG"
                },
                {
                    "id": 2,
                    "name": "BANTEN"
                }
            ]
        }

### Districts [GET /location/districts?state_id={state_id}]

+ Parameters
    + state_id: 1 (number, required)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": 1,
                    "name": "BADUNG"
                },
                {
                    "id": 2,
                    "name": "BANGLI"
                },
                {
                    "id": 3,
                    "name": "BULELENG"
                }
            ]
        }

### Cities [GET /location/cities?district_id={district_id}]

+ Parameters
    + district_id: 3 (number, required)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": 1,
                    "name": "BANJAR"
                },
                {
                    "id": 2,
                    "name": "BULELENG"
                },
                {
                    "id": 3,
                    "name": "BUSUNGBIU"
                }
            ]
        }

### Villages [GET /location/villages?city_id={city_id}]

+ Parameters
    + city_id: 1 (number, required)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": 1,
                    "name": "BALOKANG"
                },
                {
                    "id": 2,
                    "name": "BANDUNG"
                },
                {
                    "id": 3,
                    "name": "BANJAR"
                }
            ]
        }

## Transaction [/transactions]

### List Orders [GET /?page={page}&limit={limit}&start_at={start_at}&end_at={end_at}]

+ Parameters
    + page: 1 (number, required)
    + limit: 10 (number, required)
    + start_at: 1510743893 (number, required)
    + end_at: 1511943257 (number, required)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": 1,
                    "order_number": "RM-091239",
                    "product": "Isi Pulsa 10RB",
                    "transaction_at": 1511943257,
                    "admin_fee": 0,
                    "discount": 1000,
                    "amount": 10000,
                    "status": "SUCCESS",
                    "extra": {
                        "phone_number": "082123123123"
                    }
                },
                {
                    "id": 2,
                    "order_number": "RP-091239",
                    "product": "Paket Data XL-XTRA COMBO 50GB",
                    "transaction_at": 1511943257,
                    "admin_fee": 0,
                    "discount": 1000,
                    "amount": 10000,
                    "status": "SUCCESS",
                    "extra": {
                        "phone_number": "082123123123"
                    }
                },
                {
                    "id": 3,
                    "order_number": "PB-091239",
                    "product": "Pasca Bayar Telkomsel",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "phone_number": "082123123123",
                        "name": "Satrio Wisnugroho",
                        "period": "Januari - Agustus 2017",
                        "tagihan": 150000,
                        "reference_number": "981723987123"
                    }
                },
                {
                    "id": 4,
                    "order_number": "BT-091239",
                    "product": "Transfer Uang",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "sender_name": "Satrio Wisnugroho",
                        "holder_account_number": "723787123",
                        "nominal": 150000
                    }
                },
                {
                    "id": 5,
                    "order_number": "KP-091239",
                    "product": "Kioson Pay",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "e_commerce": "",
                        "name": "Satrio Wisnugroho",
                        "payment_code": "982374",
                        "price": 150000
                    }
                },
                {
                    "id": 6,
                    "order_number": "TPLN-091239",
                    "product": "Token Listrik",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "fare": 1000,
                        "token": "9081-0923-9182-1230-1233",
                        "kwh": 20,
                        "price": 150000,
                        "admin": "Setia Novanti",
                        "materai": 6000,
                        "ppn": 10,
                        "ppj": 5,
                        "angsuran": 5000,
                        "reference_number": "09812309890"
                    }
                },
                {
                    "id": 7,
                    "order_number": "BPLN-091239",
                    "product": "Tagihan Listrik",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "fare": 1000,
                        "period": "November - Desember 2017",
                        "stand_meter": 500,
                        "reference_number": "09812309890"
                    }
                },
                {
                    "id": 8,
                    "order_number": "PDAM-091239",
                    "product": "Air PDAM",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "period": "November - Desember 2017",
                        "stand_meter": 500,
                        "bill": 150000
                    }
                },
                {
                    "id": 9,
                    "order_number": "ITV-091239",
                    "product": "Internet & TV Kabel AORA TV",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_number": "8723489",
                        "soa_number": "9817238"
                        "cycle_date": 1,
                        "due_date": 1511943257,
                        "bill": 150000
                    }
                },
                {
                    "id": 10,
                    "order_number": "ITV-091239",
                    "product": "Internet & TV Kabel Indovision TV",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "period": "Juni - Juli 2017",
                        "bill": 150000
                    }
                },
                {
                    "id": 11,
                    "order_number": "ITV-091239",
                    "product": "Internet & TV Kabel Nexmedia TV",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_number": "8723489",
                        "package": "family",
                        "due_date": 1511943257,
                        "bill": 150000
                    }
                },
                {
                    "id": 12,
                    "order_number": "ITV-091239",
                    "product": "Internet & TV Kabel Orange TV",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_number": "8723489",
                        "denomination": 2,
                        "bill": 150000
                    }
                },
                {
                    "id": 13,
                    "order_number": "ITV-091239",
                    "product": "Internet & TV Kabel Topas TV",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_number": "9812398",
                        "period": "Juni - Juli 2017",
                        "bill": 150000
                    }
                },
                {
                    "id": 14,
                    "order_number": "GV-091239",
                    "product": "Game Voucher",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "voucher_code": "HSKN82J",
                        "price": 150000
                    }
                },
                {
                    "id": 15,
                    "order_number": "BPJS-091239",
                    "product": "BPJS",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "va_number": "981239",
                        "name": "Satrio Wisnugroho",
                        "number_of_participants": 3,
                        "period": "Agustus - September 2017",
                        "branch": "Sleman",
                        "reference_number": "918234989123",
                        "bill": 150000
                    }
                },
                {
                    "id": 16,
                    "order_number": "INST-091239",
                    "product": "Bayar Angsuran BAF",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "licence_plate": "AD 4459 IJ",
                        "vehicle_type": "Trails",
                        "installment_to": 5,
                        "installment_amount": 150000,
                        "tenor": 18,
                        "due_date": 1511943257,
                        "penalty": 0
                    }
                },
                {
                    "id": 17,
                    "order_number": "INST-091239",
                    "product": "Bayar Angsuran MAF",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_id": "32452",
                        "installment_to": 5,
                        "installment_amount": 150000,
                        "minimum_payment": 100000,
                        "penalty": 0
                    }
                },
                {
                    "id": 18,
                    "order_number": "INST-091239",
                    "product": "Bayar Angsuran MCF",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_id": "32452",
                        "installment_to": 5,
                        "installment_amount": 150000,
                        "minimum_payment": 100000,
                        "penalty": 0
                    }
                },
                {
                    "id": 19,
                    "order_number": "INST-091239",
                    "product": "Bayar Angsuran WOM",
                    "transaction_at": 1511943257,
                    "admin_fee": 1000,
                    "discount": 1000,
                    "amount": 150000,
                    "status": "SUCCESS",
                    "extra": {
                        "customer_id": "wisnugro",
                        "name": "Satrio Wisnugroho",
                        "reff_id": "32452",
                        "installment_to": 5,
                        "installment_amount": 150000,
                        "minimum_payment": 100000,
                        "penalty": 0
                    }
                }
            ]
        }